### PR TITLE
Optimize Rlp.LengthOf(UInt256 item)

### PR DESCRIPTION
**Pull request by benaadams**
### Benchmarks

Using `MerkleBenchmarks` for this

#### Before

| Method             | Mean      | Error    | StdDev   | Code Size | Allocated |
|------------------- |----------:|---------:|---------:|----------:|----------:|
| EOA_Leaf           | 280.77 ns | 1.803 ns | 1.598 ns |     890 B |         - |
| Contract_Leaf      | 281.04 ns | 4.823 ns | 4.511 ns |     890 B |         - |
| Storage_long_path  | 241.74 ns | 1.664 ns | 1.299 ns |     482 B |         - |
| Storage_short_path |  37.19 ns | 0.371 ns | 0.329 ns |     485 B |         - |

#### After

| Method             | Mean      | Error    | StdDev   | Code Size | Allocated |
|------------------- |----------:|---------:|---------:|----------:|----------:|
| EOA_Leaf           | 260.69 ns | 2.766 ns | 2.452 ns |     810 B |         - |
| Contract_Leaf      | 265.04 ns | 2.695 ns | 2.250 ns |     810 B |         - |
| Storage_long_path  | 230.28 ns | 1.270 ns | 1.188 ns |     469 B |         - |
| Storage_short_path |  27.24 ns | 0.197 ns | 0.184 ns |     472 B |         - |

### CODE REVIEW

**Review by Scooletz — CHANGES_REQUESTED** [review]
@benaadams I see what you did but Merkle benchmarks show otherwise. Would you be able to add some benchmarks that show the actual advantage?

**Comment by benaadams** [comment]
Should be better now; though bigger change sharing output buffer via `out` rather than return and not daisy chaining by `this` returns of large structs:

Before

| Method             | Mean      | Error    | StdDev   |
|------------------- |----------:|---------:|---------:|
| EOA_Leaf           | 276.24 ns | 2.072 ns | 1.939 ns |
| Contract_Leaf      | 275.52 ns | 2.487 ns | 2.205 ns |
| Storage_long_path  | 240.84 ns | 1.716 ns | 1.521 ns |
| Storage_short_path |  38.42 ns | 0.118 ns | 0.099 ns |

After

| Method             | Mean      | Error    | StdDev   |
|------------------- |----------:|---------:|---------:|
| EOA_Leaf           | 259.54 ns | 2.364 ns | 2.211 ns |
| Contract_Leaf      | 259.35 ns | 1.401 ns | 1.170 ns |
| Storage_long_path  | 222.39 ns | 1.068 ns | 0.892 ns |
| Storage_short_path |  23.95 ns | 0.070 ns | 0.059 ns |

**Comment by benaadams** [comment]
Though try locally to update summary since you have more columns 🤔

**Comment by benaadams** [comment]
| Method             | Mean      | Error    | StdDev   |
|------------------- |----------:|---------:|---------:|
| EOA_Leaf           | 257.25 ns | 0.907 ns | 0.708 ns |
| Contract_Leaf      | 255.70 ns | 0.836 ns | 0.698 ns |
| Storage_long_path  | 223.75 ns | 2.621 ns | 2.323 ns |
| Storage_short_path |  23.90 ns | 0.153 ns | 0.136 ns |

**Review by Scooletz — APPROVED** [review]
This is supreme. Rerun benches with applied Mem and Asm diagnosers and update the output. Merging.

**Pull request merged**
